# Generated by Django 2.2.12 on 2022-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20221025_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodetrans', models.CharField(max_length=10)),
                ('kodebrg', models.CharField(max_length=8)),
                ('qty', models.IntegerField()),
                ('subtotal', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodetrans', models.CharField(max_length=10)),
                ('tgltrans', models.DateTimeField(auto_now_add=True)),
                ('total', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='barang',
            name='kodebrg',
            field=models.CharField(default='BRG', max_length=8),
        ),
    ]
